name: pLobby
version: 1.1
author: Pedrodcp
main: br.com.pedrodcp.plobby.Main
depend: [pExternal, LuckPerms]
commands:
  plobby:
  chat:
  build:
  spawn:
  voar:
    aliases: fly
  vanish:
    aliases: v